audit_header: false
title: "Let's Talk Seniors San Diego Living Newsletter"
description: "Our mission at Let's Talk Seniors Realty Group is to be your best resource for Chula Vista real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Let's Talk Seniors Realty Group, your professional Chula Vista Real Estate Agents."
show_custom_links: true
custom_links:
  - title: Tips for Caregivers
    url: /caregivers/
  - title: Seniors of our Community
    url: /community-seniors/
  - title: Home Buying Process
    url: /home-buying/
  - title: Businesses with Seniors
    url: /business-with-seniors/
  - title: Senior Living Options
    url: /senior-living-options/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jewell Buenavista
  title:
  license_number: 'BRE #01500015'
  about_markdown: |
    Our industry-leading agents are committed to delivering extraordinary service and results to every client. With access to advanced tools and a vast network of resources, Berkshire Hathaway HomeServices California Properties agents provide the market knowledge and expertise to give you the best results on every transaction.

    Focusing on customer service and integrity ensures our agents live up to the Berkshire Hathaway name – a name voted the most trusted company in the world by Barron’s Magazine, July 2013. The dedication to service has made our company the leader in Southern California, and that success is built by our agents helping one client at a time.
  brand: "Let's Talk Seniors Realty Group"
  brokerage: Berkshire Hathaway HomeServices California Properties
  market: Chula Vista
  address: '2060 Otay Lakes Road #150, Chula Vista, CA 91915'
  phone: 800-674-2980
  phone_type:
  phone2:
  phone2_type:
  email: jewell@bhhscal.com
  url: http://www.letstalkseniors.us

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://propertyvalue.bhhscalifornia.com/jcorrea
  second_CTA_text: Home Search
  second_CTA_URL: https://jewellbuenavista.agent.bhhscalifornia.com/for-sale

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Senior Workshops"
    CTA_text: "Register for upcoming monthly senior workshops at the Chula Vista Golf Course."
    CTA_link_text: "Registration"
    CTA_url: http://www.letstalkseniors.us/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Looking for a Chula Vista Home?"
#     CTA_text2: "Search the entire MLS for your Chula Vista home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: https://jewellbuenavista.agent.bhhscalifornia.com/for-sale

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/letstalkseniors
  linkedin_url: https://www.linkedin.com/in/jewellbuenavista
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Chula Vista Real Estate Podcast with Jewell Buenavista'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Chula Vista Area Real Estate Market'
  description: "If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Let's Talk Seniors Realty Group - your professional Chula Vista Real Estate Agents."
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Chula Vista, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jewell Buenavista'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: "Let's Talk Seniors San Diego Living Newsletter"
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#562249'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#562249'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
